/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://beta.skaffolder.com/#!/register?friend=5b2fa01ac3dbdb5d5470b69c
*
* You will get 10% discount for each one of your friends
* 
*/
import { Component } from '@angular/core';
import { OnInit } from '@angular/core';
// Import Services
import { JobProfileService } from '../../services/job-profile.service';
// Import Models
import { JobProfile } from '../../domain/skaffolder-wc_db/job-profile';

// START - USED SERVICES
/**
* JobProfileService.delete
*	@description CRUD ACTION delete
*	@param ObjectId id Id
*
* JobProfileService.list
*	@description CRUD ACTION list
*
*/
// END - USED SERVICES

/**
 * This component shows a list of JobProfile
 * @class JobProfileListComponent
 */
@Component({
    selector: 'app-job-profile-list',
    templateUrl: './job-profile-list.component.html',
    styleUrls: ['./job-profile-list.component.css']
})
export class JobProfileListComponent implements OnInit {
    list: JobProfile[];
    search: any = {};
    idSelected: string;
    constructor(
        private jobprofileService: JobProfileService,
    ) { }

    /**
     * Init
     */
    ngOnInit(): void {
        this.jobprofileService.list().subscribe(list => this.list = list);
    }

    /**
     * Select JobProfile to remove
     *
     * @param {string} id Id of the JobProfile to remove
     */
    selectId(id: string) {
        this.idSelected = id;
    }

    /**
     * Remove selected JobProfile
     */
    deleteItem() {
        this.jobprofileService.remove(this.idSelected).subscribe(data => this.list = this.list.filter(el => el._id !== this.idSelected));
    }

}
